joy_it_game/accounts/urls.py
""" module: urls
** Content **
This module adds the accounts/register url 

** Details **

@author: (c) Thomas Lüth 2019 / info@tlc-it-consulting.com
@created: 2019-07-12 
""" 

from django.urls import path

from . import views


urlpatterns = [
    path('register/', views.SignUp.as_view(), name='register'),
]

joy_it_game/joy_it_game/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')), #for internationalization
    path('tlu_joyit_game/', include('tlu_joyit_game.urls')), #the main-application
    path('admin/', admin.site.urls), #given administartion site
    path('admin/docs/', include('django.contrib.admindocs.urls')), #documentation
    path('accounts/', include('accounts.urls')), #user handling
    path('accounts/', include('django.contrib.auth.urls')), #login handling
]

joy_it_game/tlu_joyit_game/urls.py
""" module: urls
** Content **
This module holds all the used URLs of the game 

** Details **

@author: (c) Thomas Lüth 2019 / info@tlc-it-consulting.com
@created: 2019-07-09 
"""

from django.urls import path
from tlu_services import tlu_local_settings

from . import views
from django.urls.conf import re_path

app_name = 'tlu_joyit_game'
urlpatterns = [
    # index is the same as the default view (blank)
    path('index', views.IndexView.as_view(), name='index'),
    # demo-page (static, no login needed)
    path('demo', views.DemoView.as_view(), name='demo'),
    # some levels / the game
    path('restart', views.restart, name='restart'), #start from the beginning
    path('levelOverview', views.LevelOverview, name = 'levelOverview'),
    path('level/<int:level_id>', views.LevelView, name='level'),
    path('start/<int:level_id>', views.startlevel, name='start'),
    path('abort/<int:level_id>', views.abortlevel, name='abort'),
    path('retry/<int:level_id>', views.retrylevel, name='retry'),
    re_path(r'^ajax/level_update/$', views.level_update, name='level_update'),
    path('deletelevel/<int:level_id>', views.deletelevel, name='deletelevel'),
]

# below logic is needed to show up a config page at first startup to set some mail-settings for the user-handling
settings=tlu_local_settings.local_settings()
startuppath=path('', views.IndexView.as_view(), name='index_main')   
# add the startpath to the list of urls  
urlpatterns.insert(0, startuppath)

joy_it_game/tlu_joyit_game/forms.py
""" module: forms
** Content **
This module helps to define the fields for the tables used on the Level-Overview form 

** Details **

@author: (c) Thomas Lüth 2019 / info@tlc-it-consulting.com
@created: 2019-07-29 
""" 
from django import forms
from tlu_joyit_game.models import Game

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('current_level', 'achieved_points', 'last_played')
        
class LevelForm (forms.ModelForm):
    class Meta:
        model = Game
        fields = ('level', 'level_start', 'level_ended', 'points', 'time_needed', 'passed')       
        

joy_it_game/tlu_joyit_game/views.py
""" module: views
** Content **
Main functionality of the Web interface. 

** Details **
Contains the major functions to run the game and the background methods to provide the 
content for specific pages.

@author: (c) Thomas Lüth 2019 / info@tlc-it-consulting.com
@created: 2019-10-01 
""" 
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils.translation import gettext as _
from django.http.response import HttpResponseNotAllowed, JsonResponse
import logging
from tlu_joyit_game.models import Level, getGameState, setGameState
from django.template.defaulttags import register
from django.contrib.auth.models import User
from joy_it_game import settings
from tlu_game.tlu_level00 import Level00
from tlu_game.tlu_level01 import Level01
from tlu_game.tlu_level02 import Level02
from tlu_game import tlu_globals
from tlu_game.tlu_level03 import Level03
from tlu_hardware import tlu_hardware_global
from tlu_hardware.tlu_hardwarebase import tlu_hardwarebase
from tlu_game.tlu_level04 import Level04

logfile=settings.BASE_DIR+"/log/game.log"
logger = logging.getLogger(__name__)
 
# List of levels that form the game, the first level (00) is for internal testings only! 
# Please make sure to update "models.py" as well for the level
levels=(Level00,Level01,Level02,Level03,Level04)

def suspendCurrentGame(request):
    """
    Terminate current level played asap
    :param request: HTTP-Call
    """
    user=request.user
    try:
        game=user.game
    except:
        return
    if game.is_running():
        game.abort()
        game.save()

class IndexView(generic.TemplateView):
    """
    Main View/startscreen
    """
    template_name = 'tlu_joyit_game/index.html'
        
    def get(self, request, *args, **kwargs):
        """
        Renders the view and starts the hardware by displaying the clock
        Kills as well all possible running processes
        :param request: HTTP-request
        """
        logger.info("Index View called")
        tlu_globals.init()
        tlu_hardware_global.init()
        suspendCurrentGame(request)
        level=Level00(request.user.id)
        level.cleanup(True)
        level.startup()  
        tlu_globals.globMgr.tlu_glob().stopClock()
        return generic.TemplateView.get(self, request, *args, **kwargs)
    
class DemoView(generic.TemplateView):
    """
    Demo-screen / work in progress
    """
    template_name = 'tlu_joyit_game/demo.html'
  
@register.filter(name='levelConvert')
def get_resultname(key) -> str:
    """
    Show the name of the result on the screen, returns the name as string
    :param key: result of the level (number)
    """
    if (key==None):
        return ""
    return Level.resultdict[key]

'''
@register.filter(name='totalTime')
def get_totaltime(level) -> str:
    """
    Calculate the total time needed for the level as a string
    :param level:
    """
    if (level == None) or (level.level_start == None) or (level.level_ended == None):
        return "0"
    return str((level.level_ended-level.level_start).total_seconds())
'''    
    
def LevelOverview(request):
    """
    Render the Level-overwiew which contains a table for the current state and 
    as well another one for the levels played so far.
    
    :param request: HTTP-request
    """
    if request.method=='GET':
        tlu_globals.init()
        tlu_hardware_global.init()
        suspendCurrentGame(request)
        level=Level00(request.user.id)
        level.startup()  
        template_name = 'tlu_joyit_game/level_overview.html'
        user=get_object_or_404(User, pk=request.user.id)
        game=user.game
        logging.debug("LevelOverview, current game="+str(game))
        button_text=_("Continue the game now")
        path=""
        try:
            level_set=game.level_set.all().order_by('-id')
        except (KeyError, Level.DoesNotExist):
            level_set=None
        cur_level=game.current_level
        if cur_level == None:
            current_level_num=0
        else:
            current_level_num = cur_level.levelnum
        next_level_num = current_level_num
        if (cur_level != None) and (cur_level.result == Level.PASSED):
            next_level_num += 1
            if game.completed(next_level_num):
                next_level_num -= 1
                button_text=_("Play level again")
                path=reverse('tlu_joyit_game:retry', kwargs={'level_id':next_level_num})
        if len(path) == 0:
            path=reverse('tlu_joyit_game:level', kwargs={'level_id':next_level_num})
        last_played=None
        if (cur_level != None):
            last_played=cur_level.level_start
        if last_played == None:
            last_played=_("Not yet played")
            path='/tlu_joyit_game/restart'
        if (level_set == None) or (len(level_set)<1):
            button_text=_("Start now")
        game=request.user.game
        achieved_points=game.getAchievedPoints()
        minutes_active_game=game.getMinutesPlayedCurrentGame()
        minutes_played=game.getMinutesPlayedOverall()
        num_starts=game.getNumStarts()
        return render(request, template_name, {'current_level': str(current_level_num), 
                                               'last_played': last_played,
                                               'achieved_points':achieved_points,
                                               'minutes_active_game':str(minutes_active_game),
                                               'minutes_played':str(minutes_played),
                                               'num_starts':str(num_starts),
                                               'button_text':button_text,
                                               'next_level_url' : path})
    return HttpResponseNotAllowed(['POST'])

def restart(request):
    """
    Process the restart request from the user
    :param request: HTTP-request
    """
    tlu_globals.init()
    tlu_hardware_global.init()
    game=request.user.game
    game.restart()
    return HttpResponseRedirect(reverse('tlu_joyit_game:level', kwargs={'level_id':1}))

class OutOfRangeError(Exception):
    """
    Class to specify that the level is not within the allowed range
    """
    pass

def checkLevel(request, level_id):
    """
    Check that the provided level is within the allowed range.
    If not raises an OutOfRangeError
    :param request: HTTP-request
    :param level_id: level-number (picked from url)
    """
    if level_id == 1:
        #startup level is ever ok
        return
    user=request.user
    try:
        tlu_globals.init()
        tlu_hardware_global.init()
        game=user.game
    except:
        return
    if game.current_level == None:
        if (level_id > 1):
            status=getGameState(user.id)
            status.msg=_("You just started from the beginning, so level has to be one, please restart the game!")
            setGameState(user.id,status)
            raise OutOfRangeError
        else:
            return
    if (level_id > game.current_level.levelnum +1) or (level_id < game.current_level.levelnum) or game.completed(level_id):
        status=getGameState(user.id)
        status.msg=_("The requested level is not in line with our expectations, please restart the game!")
        setGameState(user.id,status)
        raise OutOfRangeError
    
def renderLevel(request, level_id):
    """
    Show the Level-page where we can start the individual level
    :param request: HTTP-request
    :param level_id: level-number to start
    """
    template_name = "level_"+"{:02d}".format(level_id)+".html"
    user=request.user
    game=user.game
    try:
        tlu_globals.init()
        tlu_hardware_global.init()
        checkLevel(request, level_id)
    except OutOfRangeError:
        template_name = "level_error.html"
        error=_("We are sorry, but the provided level-id does not fit your overall progress, you have to restart.")
        return render(request, template_name, {'error':error} )
    dips = game.getDipSwitch(level_id)
    leftDip=_("left:")+" "+tlu_hardwarebase.showleft_dip(dips)
    rightDip=_("right:")+" "+tlu_hardwarebase.showright_dip(dips)
    overall_progress=game.getOverallProgress()
    info=_("Please press start and check the DIP-settings...")
    button_text=_("Start Level")+" "+str(level_id)
    button_url='/tlu_joyit_game/start/'+str(level_id)
    return render(request, template_name, {'leftDip':leftDip, 
                                           'rightDip':rightDip, 
                                           'overall_progress':overall_progress, 
                                           'info':info, 
                                           'button_text':button_text,
                                           'button_url':button_url} )
   
    
def startlevel(request, level_id):
    """
    Starts the game as per request given and returns the Level via renderLevel
    :param request: HTTP-request
    :param level_id: level-number
    """
    user=request.user
    try:
        tlu_globals.init()
        tlu_hardware_global.init()
        checkLevel(request, level_id)
        user.game.start(levels[level_id], level_id)
        logging.debug("Game started: "+str(user.game))
    except OutOfRangeError:
        template_name = "level_error.html"
        error=_("We are sorry, but the provided level-id does not fit your overall progress, you have to restart.")
        return render(request, template_name, {'error':error} )
    except Exception as e:
        template_name = "level_error.html"
        error=_("We are sorry, but the user has to be known/logged in, you have to restart.")+" Error: "+str(e)
        return render(request, template_name, {'error':error} )
    return renderLevel(request, level_id)

def abortlevel(request, level_id):   
    """
    Process the abort request
    :param request: HTTP-request

joy_it_game/tlu_joyit_game/templates/tlu_joyit_game/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>tlu_joyit_game</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon_16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon_32.png">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Article-List.css">
    <link rel="stylesheet" href="/assets/css/Brands.css">
    <link rel="stylesheet" href="/assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="/assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <link rel="stylesheet" href="/assets/css/Social-Icons.css">
</head>

<body>{% include "header_inc.html" %}
    <div id="content" style="margin-bottom: 0px;padding-bottom: 5px;background-image: url(&quot;/assets/img/nature/image4.jpg&quot;);">{% load i18n %}{% if user.is_authenticated %} 
        <div class="jumbotron" id="Loggedin">
            <h1>{% trans "Welcome" %} {{ user.username }}!</h1>
            <p>{% trans 'Hey' %} {{ user.username }}{% trans ", you are now able to start the little game or to continue from where you have left off. Please press the below button to get started :) " %}<br></p>
            <div style="height: 140px;"><img src="/assets/img/tlu/RB-JoyPi-2g.png" style="height: 120px;"></div>
            <p>
                <div class="btn-group border rounded-circle shadow-sm" role="group"><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:levelOverview' %}" style="background-color: rgb(137,143,65);padding-bottom: 6px;">{% trans "Get started" %}</a><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:demo'%}">{% trans "Get impressions" %}</a></div>
            </p>
        </div>{% else %}
        <div class="jumbotron text-center" id="Loggedout" style="margin-bottom: 10px;padding: 10px;">
            <h1>{% trans "You have to log in" %}</h1>
            <p>{% trans "We are sorry, but in order to move ahead you have to log in or register yourself" %}</p>
            <div class="btn-group" role="group"><a class="btn btn-primary" role="button" href="{% url 'login' %}" style="background-color: rgb(19,255,14);">{% trans "Log &nbsp;in" %}</a><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:demo'%}">{% trans "Get impressions" %}</a></div>
        </div><div>{% endif %}</div></div><div>{% include "footer_inc.html" %}{% load i18n %}</div>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/tlu_helper.js"></script>
    <script src="/assets/js/tlu_settingshelper.js"></script>
    <script src="/assets/js/tlu_levelsupport.js"></script>
</body>

</html>

joy_it_game/tlu_joyit_game/templates/tlu_joyit_game/level_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>tlu_joyit_game</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon_16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon_32.png">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Article-List.css">
    <link rel="stylesheet" href="/assets/css/Brands.css">
    <link rel="stylesheet" href="/assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="/assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <link rel="stylesheet" href="/assets/css/Social-Icons.css">
</head>

<body>{% include "header_inc.html" %}
    <div id="content">{% load i18n %}{% if user.is_authenticated %} 
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="jumbotron" id="SetSettings">
                        <h1>{% block headline %}{% endblock %}</h1>
                        <p>{% trans "This is your task to solve the puzzle:" %}<br></p>
                        <div id="instruction">
                            <p>{% block instruction %}{% endblock %}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="jumbotron" id="SetSettings">
                        <h5>{% trans 'dip settings' %}</h5>
                        <p id="dipsettings" style="font-size: 12px;">{% trans "The two dip-switches have to be set as below in order to get this level done:" %}<br><img src="/assets/img/Dip-switches.jpg" style="width: 80px;"><br>{{ leftDip }} &nbsp;<span style="width: 55px;"></span>&nbsp; {{ rightDip }}<br></p>
                        <h5>{% trans 'Your progress' %}</h5>
                        <div class="progress">
                            <div class="progress-bar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" id="current_progress" style="width: 0%;">0%</div>
                        </div>
                        <div class="progress">
                            <div class="progress-bar" aria-valuenow="{{ overall_progress }}" aria-valuemin="0" aria-valuemax="100" id="overall_progress" style="width:{{ overall_progress }}%">{{ overall_progress }}%</div>
                        </div>
                        <h5>{% trans 'Some information' %}</h5>
                        <div id="status">
                            <p>{{ info }}</p>
                        </div>
                        <p></p><a class="btn btn-primary" role="button" id="startbutton" href="{{ button_url }}">{{ button_text }}</a></div>
                </div>
            </div>
        </div>{% else %}
        <div class="jumbotron text-center" id="Loggedout" style="margin-bottom: 10px;padding: 10px;">
            <h1>{% trans "You have to log in" %}</h1>
            <p>{% trans "We are sorry, but in order to move ahead you have to log in or register yourself" %}</p>
            <div class="btn-group" role="group"><a class="btn btn-primary" role="button" href="{% url 'login' %}" style="background-color: rgb(19,255,14);">{% trans "Log &nbsp;in" %}</a><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:demo'%}">{% trans "Run demo" %}</a></div>
        </div>{% endif %}</div><div>{% include "footer_inc.html" %}{% load i18n %}</div>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/tlu_helper.js"></script>
    <script src="/assets/js/tlu_settingshelper.js"></script>
    <script src="/assets/js/tlu_levelsupport.js"></script>
</body>

</html>

joy_it_game/tlu_joyit_game/templates/tlu_joyit_game/level_error.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>tlu_joyit_game</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon_16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon_32.png">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Article-List.css">
    <link rel="stylesheet" href="/assets/css/Brands.css">
    <link rel="stylesheet" href="/assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="/assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <link rel="stylesheet" href="/assets/css/Social-Icons.css">
</head>

<body>{% include "header_inc.html" %}
    <div id="content">{% load i18n %}{% if user.is_authenticated %} 
        <div class="jumbotron" id="SetSettings">
            <h1 style="color: red;">{% trans "An error occured" %}</h1>
            <p>{% trans "We are sorry, but the following error occured" %}<br></p>
            <div id="instruction" style="background-color: rgb(255,158,158);color: rgb(255,255,255);padding: 0px;">
                <p>{{ error }}</p>
            </div>
            <p></p><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:level' 1 %}" style="background-color: rgb(137,143,65);padding-bottom: 6px;">{% trans "Restart the game" %}</a></div>{% else %}
        <div class="jumbotron text-center"
            id="Loggedout" style="margin-bottom: 10px;padding: 10px;">
            <h1>{% trans "You have to log in" %}</h1>
            <p>{% trans "We are sorry, but in order to move ahead you have to log in or register yourself" %}</p>
            <div class="btn-group" role="group"><a class="btn btn-primary" role="button" href="{% url 'login' %}" style="background-color: rgb(19,255,14);">{% trans "Log &nbsp;in" %}</a><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:demo'%}">{% trans "Run demo" %}</a></div>
        </div>{% endif %}</div><div>{% include "footer_inc.html" %}{% load i18n %}</div>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/tlu_helper.js"></script>
    <script src="/assets/js/tlu_settingshelper.js"></script>
    <script src="/assets/js/tlu_levelsupport.js"></script>
</body>

</html>

joy_it_game/tlu_joyit_game/templates/tlu_joyit_game/level_overview.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>tlu_joyit_game</title>
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon_16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon_32.png">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="/assets/fonts/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Article-List.css">
    <link rel="stylesheet" href="/assets/css/Brands.css">
    <link rel="stylesheet" href="/assets/css/Footer-Clean.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="/assets/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="/assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="/assets/css/Registration-Form-with-Photo.css">
    <link rel="stylesheet" href="/assets/css/styles.css">
    <link rel="stylesheet" href="/assets/css/Social-Icons.css">
</head>

<body>{% include "header_inc.html" %}
    <div id="content" style="margin-bottom: 0px;padding-bottom: 5px;background-image: url(&quot;/assets/img/nature/image4.jpg&quot;);">{% load i18n %}{% if user.is_authenticated %} 
        <div class="jumbotron" id="SetSettings">
            <h1>{% trans 'Overview' %}</h1>
            <p>{% trans "Please find some details below:" %}<br></p>
            <div><div class="table-responsive">
    <table class="table" id="valuetable">
        <thead>
            <tr>
                <th>{% trans "Item" %}</th>
                <th>{% trans "Value" %}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{% trans "Current level" %}</td>
                <td>{{ current_level }}</td>
            </tr>
            <tr>
                <td>{% trans "Last played" %}</td>
                <td>{{ last_played }}</td>
            </tr>
            <tr>
                <td>{% trans "Achieved points" %}</td>
                <td>{{ achieved_points }}</td>
            </tr>
            <tr>
                <td>{% trans "Minutes played this game" %}</td>
                <td>{{ minutes_active_game }}</td>
            </tr>
            <tr>
                <td>{% trans "Minutes played overall" %}</td>
                <td>{{ minutes_played }}</td>
            </tr>
            <tr>
                <td>{% trans "Number of games played" %}</td>
                <td>{{ num_starts }}</td>
            </tr>
        </tbody>
    </table>
</div><a class="btn btn-primary" role="button" id="startbutton" href="{{ next_level_url }}">{{ button_text }}</a><a class="btn btn-primary" role="button" id="startbutton" href="{% url 'tlu_joyit_game:restart'  %}">{% trans 'Restart the game' %}</a></div>
        </div>{% else %}
        <div class="jumbotron text-center" id="Loggedout" style="margin-bottom: 10px;padding: 10px;">
            <h1>{% trans "You have to log in" %}</h1>
            <p>{% trans "We are sorry, but in order to move ahead you have to log in or register yourself" %}</p>
            <div class="btn-group" role="group"><a class="btn btn-primary" role="button" href="{% url 'login' %}" style="background-color: rgb(19,255,14);">{% trans "Log &nbsp;in" %}</a><a class="btn btn-primary" role="button" href="{% url 'tlu_joyit_game:demo'%}">{% trans "Run demo" %}</a></div>
        </div>{% endif %}</div><div>{% include "footer_inc.html" %}{% load i18n %}</div>
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/pikaday.min.js"></script>
    <script src="/assets/js/theme.js"></script>
    <script src="/assets/js/tlu_helper.js"></script>
    <script src="/assets/js/tlu_settingshelper.js"></script>
    <script src="/assets/js/tlu_levelsupport.js"></script>
</body>

</html>